### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by bangyen**

### CODE REVIEW

**Comment by Sherlemious** [comment]
This conflicts with the current version. Added to that, I already removed the extra part of the code.

**Comment by bangyen** [comment]
of course it conflicts, this pull request is four days old

**Comment by Sherlemious** [comment]
Well, yes but I already planned on changing that part when I committed to it like 15 days ago.

**Comment by Sherlemious** [comment]
I'm sorry I didn't approve this commit. I'd be glad if you helped with the REPEAT UNTIL function. I'm not gonna start with that until a while so I'm gonna approve whatever you add to that function. If you're interested, there's a file called Repeat Function inside the functions folder. Edit that not the main as I'll be working on it.

**Pull request closed without merging**
